const FakeData3 = [
    {
        name: 'Abu Hasnat Nobin',
        Email: 'tafsanmahmudnobin090@gmail.com',
        serviceName: 'Linkedin SEO',
        PaymentID: '#aD@a23s4fdXDZFd008',
        Status: 'Pending',
    },
    {
        name: 'Hasnat Nobin',
        Email: 'tafsannobin@gmail.com',
        serviceName: 'Linkedin SEO',
        PaymentID: '#aD@a23s4fdXDZFd008',
        Status: 'On-Going',
    },
    {
        name: 'Hasnat Nobin',
        Email: 'tafsannobin@gmail.com',
        serviceName: 'Linkedin SEO',
        PaymentID: '#aD@a23s4fdXDZFd008',
        Status: 'Done',
    },
    {
        name: 'Hasnat Nobin',
        Email: 'tafsannobin@gmail.com',
        serviceName: 'Linkedin SEO',
        PaymentID: '#aD@a23s4fdXDZFd008',
        Status: 'Pending',
    },
    {
        name: 'Hasnat Nobin',
        Email: 'tafsannobin@gmail.com',
        serviceName: 'Linkedin SEO',
        PaymentID: '#aD@a23s4fdXDZFd008',
        Status: 'Pending',
    },
    {
        name: 'Hasnat Nobin',
        Email: 'tafsannobin@gmail.com',
        serviceName: 'Linkedin SEO',
        PaymentID: '#aD@a23s4fdXDZFd008',
        Status: 'Done',
    },
    {
        name: 'Hasnat Nobin',
        Email: 'tafsannobin@gmail.com',
        serviceName: 'Linkedin SEO',
        PaymentID: '#aD@a23s4fdXDZFd008',
        Status: 'Pending',
    },
    {
        name: 'Hasnat Nobin',
        Email: 'tafsannobin@gmail.com',
        serviceName: 'Linkedin SEO',
        PaymentID: '#aD@a23s4fdXDZFd008',
        Status: 'On-Going',
    },
    {
        name: 'Hasnat Nobin',
        Email: 'tafsannobin@gmail.com',
        serviceName: 'Linkedin SEO',
        PaymentID: '#aD@a23s4fdXDZFd008',
        Status: 'On-Going',
    },
    {
        name: 'Hasnat Nobin',
        Email: 'tafsannobin@gmail.com',
        serviceName: 'Linkedin SEO',
        PaymentID: '#aD@a23s4fdXDZFd008',
        Status: 'On-Going',
    },
    {
        name: 'Hasnat Nobin',
        Email: 'tafsannobin@gmail.com',
        serviceName: 'Linkedin SEO',
        PaymentID: '#aD@a23s4fdXDZFd008',
        Status: 'Pending',
    },
    {
        name: 'Hasnat Nobin',
        Email: 'tafsannobin@gmail.com',
        serviceName: 'Linkedin SEO',
        PaymentID: '#aD@a23s4fdXDZFd008',
        Status: 'Done',
    },
]

export default FakeData3